#!/bin/bash

KEEP_ZSHRC="yes"; bash ~/dotfiles/oh-my-zsh.sh

cat ~/dotfiles/.zshrc >> ~/.zshrc
cp ~/dotfiles/.zlogout ~/.zlogout

sudo apt install -y \
  tcpdump \
  telnet

sudo bash ~/dotfiles/configgit

git clone https://github.com/rafaelzimmermann/linux-bootstrap.git
cd linux-bootstrap
bash bootstrap-server