#!/bin/bash

KEEP_ZSHRC="yes"; bash ~/dotfiles/oh-my-zsh.sh

cat ~/dotfiles/.zshrc >> ~/.zshrc
cp ~/dotfiles/.zlogout ~/.zlogout

sudo apt install -y \
  tcpdump \
  telnet

sudo bash ~/dotfiles/configgit
